### ISSUE TITLE
Event transitions should be deterministic

### ISSUE THREAD

**Issue by hoangelos** [alfonso-presa/restflow#2]
When you do a Guard, the events aren't processed in the order they are in the array.  So there doesn't appear to be a way to prioritize events.  The data structure that these are stored in could help in this.

**Comment by alfonso-presa** [comment]
Hi @hoangelos. Even though it sounds like a correct statement, I don't see the use case... Events are supposed to be triggered in the order you raise them in the flow. Do you mind sharing the flow code you're using, or some example illustrating the problem?

**Comment by alfonso-presa** [comment]
@hoangelos Sorry, I misunderstood your point. You were right. There's a limitation of `Class.getDeclaredMethods` that prevents the order of declaration to be present. I added an optional attribute to On OnState and Guard annotations so you can control the execution order if it's necessary.

Will be available in v0.1.0.
